[package]
name = "cxfinance"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cxrvus/cxfinance"

[dependencies]
egui = "0.27.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
