[package]
name = "cxfinance"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cxrvus/cxfinance"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
